name: Preprocess Dataset

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Install Dependencies
      - name: Install dependencies
        run: |
          pip install pandas scikit-learn joblib nltk requests sastrawi git+https://github.com/ariaghora/mpstemmer.git python-Levenshtein
          python -m nltk.downloader punkt
          python -m nltk.downloader stopwords

      # Run Automation Preprocessing
      - name: Run automation preprocessing
        run: |
          python preprocessing/automate_syahrul-fahmi.py

      # Setup Github LFS
      - name: Set up Git LFS
        run: |
           git config --global user.name ${{ secrets.USERNAME }}
           git config --global user.email ${{ secrets.EMAIL }}
           git lfs install
           git lfs track "preprocessing/**"
           git add .gitattributes
           git commit -m "Track large files in mlruns with Git LFS" || true
           git push

      # Push Processed Dataset
      - name: commit pre-processed dataset
        run: |
          git add preprocessing/ulasan_processed_dataset.csv
          git commit -m "update preprocessed dataset"
          git push
